let PAWN = 0,
  ROUKE = 1,
  KNIGHT = 2,
  BISHOP = 3,
  QUEEN = 4,
  KING = 5;
let IN_PLAY = 0;

let json = {
  white: [
    {
      piece: ROUKE,
      row: 0,
      col: 0,
      status: IN_PLAY,
    },
    {
      piece: KNIGHT,
      row: 0,
      col: 1,
      status: IN_PLAY,
    },
    {
      piece: BISHOP,
      row: 0,
      col: 2,
      status: IN_PLAY,
    },
    {
      piece: KING,
      row: 0,
      col: 3,
      status: IN_PLAY,
    },
    {
      piece: QUEEN,
      row: 0,
      col: 4,
      status: IN_PLAY,
    },
    {
      piece: BISHOP,
      row: 0,
      col: 5,
      status: IN_PLAY,
    },
    {
      piece: KNIGHT,
      row: 0,
      col: 6,
      status: IN_PLAY,
    },
    {
      piece: ROUKE,
      row: 0,
      col: 7,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 0,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 1,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 2,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 3,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 4,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 5,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 6,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 1,
      col: 7,
      status: IN_PLAY,
    },
  ],
  black: [
    {
      piece: ROUKE,
      row: 7,
      col: 0,
      status: IN_PLAY,
    },
    {
      piece: KNIGHT,
      row: 7,
      col: 1,
      status: IN_PLAY,
    },
    {
      piece: BISHOP,
      row: 7,
      col: 2,
      status: IN_PLAY,
    },
    {
      piece: KING,
      row: 7,
      col: 3,
      status: IN_PLAY,
    },
    {
      piece: QUEEN,
      row: 7,
      col: 4,
      status: IN_PLAY,
    },
    {
      piece: BISHOP,
      row: 7,
      col: 5,
      status: IN_PLAY,
    },
    {
      piece: KNIGHT,
      row: 7,
      col: 6,
      status: IN_PLAY,
    },
    {
      piece: ROUKE,
      row: 7,
      col: 7,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 0,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 1,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 2,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 3,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 4,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 5,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 6,
      status: IN_PLAY,
    },
    {
      piece: PAWN,
      row: 6,
      col: 7,
      status: IN_PLAY,
    },
  ],
};
export { json };
